symbolPreset: nerd
theme: 
  dark: titanium
  light: light-one
setupVersion: 1
modelRoles: 
  advisor: openai-codex/gpt-5.5:xhigh
  default: deepseek/deepseek-v4-flash:high
  slow: openai-codex/gpt-5.5:xhigh
  vision: openai-codex/gpt-5.5:medium
  plan: openai-codex/gpt-5.5:xhigh
  designer: openai-codex/gpt-5.5:xhigh
  task: deepseek/deepseek-v4-flash:xhigh
  tiny: deepseek/deepseek-v4-flash:high
  commit: deepseek/deepseek-v4-flash:high